### ISSUE TITLE
Missing headers in conf causes error

### ISSUE THREAD

**Issue by robin-rozo** [hprieurgarrouste/fhirBrowser#1]
When "headers" is missing in configuration and an auth configuration; there is a js error in the console.

![image](https://user-images.githubusercontent.com/6724355/195785764-77aa3e9b-a361-482e-b898-a37ae55e3ec8.png)

**Comment by hprieurgarrouste** [comment]
fixed

**Comment by hprieurgarrouste** [comment]
closed
