### ISSUE TITLE
References : Improve references detection, e.g. "partof" or "managedby" are missing

### ISSUE THREAD

**Issue by hprieurgarrouste** [hprieurgarrouste/fhirBrowser#14]

**Comment by davidfermet** [comment]
reference detection currently parses search parameters, which lack the data type of earch search parameter.
By luck, most of the time an Organization is refered to by organization, and in such a case, the current method works.

A cleaner way would be to use the StructureDefinition of each ressource, parse all elements in resource.differential.element and search for Reference items and get the right variable name (incl partof, managedby...)

Unfortunately all servers don't implement properly the StructureDefinition endpoint (HAPI does, ANS doesn't, NHS barely implements anything...) so using a default fallback method on the official (base) structure definition of a given resource is not a bad idea

**Comment by hprieurgarrouste** [comment]
resolved
