### ISSUE TITLE
Buttons do not work

### ISSUE THREAD

**Issue by Argatorne** [hprieurgarrouste/fhirBrowser#23]
When the user choose a specific resource in the list after chiise a resource type, buttons which allow the following actions don't work :
- Copy to clipboard, 
- Download 
- Share (less important)

Nevertheless, options **_'Copy to clipborad_**' and **_'Download'_** works for the bundle.

**Comment by hprieurgarrouste** [comment]
the commit f1fcb64 solved the issue
